"""empty message

Revision ID: 778ec6112376
Revises: 
Create Date: 2024-01-22 14:39:02.738588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778ec6112376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('employees', sa.String(), nullable=True),
    sa.Column('revenue', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('number_sent', sa.Integer(), nullable=True),
    sa.Column('number_replied', sa.Integer(), nullable=True),
    sa.Column('number_unsubscribed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('tone', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_template.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('recipient')
    op.drop_table('email_template')
    op.drop_table('company')
    # ### end Alembic commands ###
